# Generated by Django 3.0.4 on 2020-04-30 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepost',
            name='like_users',
            field=models.ManyToManyField(related_name='like_codeposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
